enum Status {
  START_CALC = "START_CALC",
  CALC_FINISHED = "CALC_FINISHED",
  CALC_FAILED = "CALC_FAILED",
  CALCULATING = "CALCULATING",
  CALCULATING_SENDING_STEP = "CALCULATING_SENDING_STEP",
  SENDING_MIN_MAX_X_Y = "SENDING_MIN_MAX_X_Y",
  SENDING_AVAILABLE_ALGORITHMS = "SENDING_AVAILABLE_ALGORITHMS",
}
export default Status;
