enum Status {
    START_CALC = "START_CALC", CALC_FINISHED = "CALC_FINISHED", CALC_FAILED = "CALC_FAILED", CALCULATING = "CALCULATING", CALCULATING_SENDING_STEP = "CALCULATING_SENDING_STEP"
}
export default Status;